### PR TITLE
Configure gpt4 review on /review comment

### PR DESCRIPTION
**Pull request by ccubu**

### CODE REVIEW

**Comment by ccubu** [comment]
gpt review

**Comment by ccubu** [comment]
gpt review

**Comment by ccubu** [comment]
> /review

sadly, the trigger that you created with this comment ran the workflow from main branch, which means that the workflow that you see on this PR will only work once is merged on main. You can inspect the worfklow file used on the chatgpt run that your comment triggered here -> https://github.com/freeverseio/laos/actions/runs/6657084824 and you will be able to see that it's not the workflow file from the PR

**Review by asiniscalchi — APPROVED** [review]

**Pull request merged**
