### PR TITLE
Upgrade Polkadot SDK to Stable2407 and Enhance Configurations


### PR DESCRIPTION
**Pull request by magecnion**
### **PR Type**
Enhancement, Bug fix

___

### **Description**
- Upgraded the Polkadot SDK to the `stable2407` branch across multiple files, ensuring compatibility with the latest stable features.
- Added `XcmRecorder` to various XCM configurations to enhance XCM handling.
- Simplified and cleaned up configurations and tests, removing unused parameters and functions.
- Updated dependencies in `Cargo.toml` to align with the new SDK version.
- Suppressed deprecated warnings in several modules to maintain code quality.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>14 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>laos.rs</strong><dd><code>Simplify ChainSpec Type Definition</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

node/src/chain_spec/laos.rs

- Simplified the `ChainSpec` type definition.

</details>

  </td>
  <td><a href="https://github.com/freeverseio/laos/pull/773/files#diff-2ccef9e2947edd74c86ff7b5a814c38a09079830181b3f5d86bb098384e7a868">+1/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>eth.rs</strong><dd><code>Suppress Deprecated Warnings in Eth Module</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

node/src/eth.rs

- Added `#[allow(deprecated)]` attribute to suppress warnings.

</details>

  </td>
  <td><a href="https://github.com/freeverseio/laos/pull/773/files#diff-3212b38da1f5b949900bc3202eef6628b7b56bbc4fa07fe1613b2441d91fce62">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>service.rs</strong><dd><code>Suppress Warnings and Remove Unused Parameters</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

node/src/service.rs

<li>Added <code>#[allow(deprecated)]</code> attribute to suppress warnings.<br> <li> Removed <code>sync_oracle</code> parameter from functions.<br>

</details>

  </td>
  <td><a href="https://github.com/freeverseio/laos/pull/773/files#diff-594440db8adfc5d1b37711309312bfa06b49e488309186ad062a896778cf9fbf">+5/-8</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>tests.rs</strong><dd><code>Simplify Reset Issuance Function in Tests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pallets/parachain-staking/src/tests.rs

- Simplified the `reset_issuance` function.

</details>

  </td>
  <td><a href="https://github.com/freeverseio/laos/pull/773/files#diff-a2fcd9e2ec1e588e9fcfed674d8d0058713d685aaba3ed374ba248d4c279e02f">+1/-10</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>cumulus_xcmp_queue.rs</strong><dd><code>Add New Parameter Types for XCMP Queue</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

runtime/laos/src/configs/cumulus_xcmp_queue.rs

<li>Added new parameter types for <code>MaxActiveOutboundChannels</code> and <br><code>MaxPageSize</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/freeverseio/laos/pull/773/files#diff-cddc5de870ba2ea110c4b0b6cad78cf776f0f66d0cce7e50bcfea5c4ca060c80">+10/-1</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>treasury.rs</strong><dd><code>Clean Up Treasury Configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

runtime/laos/src/configs/treasury.rs

- Removed unused parameters and types.

</details>

  </td>
  <td><a href="https://github.com/freeverseio/laos/pull/773/files#diff-094b4a74f7e7a446c70dd2ca710d6a7c87a1c46369ec9a8125621479e247219a">+1/-10</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>xcm_config.rs</strong><dd><code>Add XcmRecorder to XCM Configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

runtime/laos/src/configs/xcm_config.rs

- Added `XcmRecorder` type to the configuration.

</details>

  </td>
  <td><a href="https://github.com/freeverseio/laos/pull/773/files#diff-7be85ebadbdf1d1e426a2b4f3e4f1d6b496df8603fa762c7e0efcceb40533a48">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>lib.rs</strong><dd><code>Add Initialize Pending Block Function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

runtime/laos/src/lib.rs

- Added `initialize_pending_block` function to runtime APIs.

</details>

  </td>
  <td><a href="https://github.com/freeverseio/laos/pull/773/files#diff-003c87018a12c01c5266d5e1f3aba274f64cc6651fdb6b34abb88a6d1a10d073">+4/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>migrations.rs</strong><dd><code>Add New Migration Type for XCMP Queue</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

runtime/laos/src/migrations.rs

- Added new migration type `MigrateV4ToV5`.

</details>

  </td>
  <td><a href="https://github.com/freeverseio/laos/pull/773/files#diff-274ce6fb28d6ba917e57636a9d7d67c1aca77b83f23fac06dcb0a6cd57efb6cd">+9/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>pallet_treasury.rs</strong><dd><code>Remove Unused Treasury Weight Functions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

runtime/laos/src/weights/pallet_treasury.rs

- Removed weight functions for treasury proposals.

</details>

  </td>
  <td><a href="https://github.com/freeverseio/laos/pull/773/files#diff-53f58d1ce2b5815a52a3602cdb0d7ad617b0279f2debf3eaabab66067f628b95">+0/-45</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>mod.rs</strong><dd><code>Add XcmRecorder to Asset Hub XCM Config</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

xcm-simulator/src/asset_hub/xcm_config/mod.rs

- Added `XcmRecorder` type to the configuration.

</details>

  </td>
  <td><a href="https://github.com/freeverseio/laos/pull/773/files#diff-f856d5d783c33f252fdeaf295d985945000850363af3ee8e8e0ed3ae31caf90d">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>xcm_config.rs</strong><dd><code>Add XcmRecorder to Laosish XCM Config</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

xcm-simulator/src/laosish/configs/xcm_config.rs

- Added `XcmRecorder` type to the configuration.

</details>

  </td>
  <td><a href="https://github.com/freeverseio/laos/pull/773/files#diff-a7b3227fa0fc64037406baf87be6d4f1ed1a00856a5a8aa16729f2a4a93a2b49">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>parachain.rs</strong><dd><code>Add XcmRecorder to Parachain Config</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

xcm-simulator/src/parachain.rs

- Added `XcmRecorder` type to the configuration.

</details>

  </td>
  <td><a href="https://github.com/freeverseio/laos/pull/773/files#diff-1f715cbd16cb932f4a1d5f5e0e6d7ea2fbbf90561b573e33ad57bf9d55266a0b">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>relay_chain.rs</strong><dd><code>Add XcmRecorder to Relay Chain Config</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

xcm-simulator/src/relay_chain.rs

- Added `XcmRecorder` type to the configuration.

</details>

  </td>
  <td><a href="https://github.com/freeverseio/laos/pull/773/files#diff-16f103ac112ee0122f0fb3ba5833433d9abcd77f8b45ec31aff72c8518a2cc4d">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></details></td></tr><tr><td><strong>Configuration changes</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>download_polkadot.sh</strong><dd><code>Update Default Polkadot SDK Version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

zombienet/download_polkadot.sh

- Updated default Polkadot SDK version to `stable2407-3`.

</details>

  </td>
  <td><a href="https://github.com/freeverseio/laos/pull/773/files#diff-4df584d9754562d5c8901efa9bdc7bab824e81df17c905dbf22b878a6ef8c239">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></details></td></tr><tr><td><strong>Dependencies</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>Cargo.toml</strong><dd><code>Update Dependencies to Stable2407 Branch</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

Cargo.toml

<li>Updated Polkadot SDK dependencies to <code>stable2407</code> branch.<br> <li> Updated <code>jsonrpsee</code> version to <code>0.23.2</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/freeverseio/laos/pull/773/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542">+147/-147</a></td>

</tr>
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Review by asiniscalchi — APPROVED** [review]

**Review by asiniscalchi — APPROVED** [review]

**Review by asiniscalchi — CHANGES_REQUESTED** [review]
Treasury entry disappered
image

**Review by asiniscalchi — APPROVED** [review]

**Review by tsenovilla — APPROVED** [review]

**Pull request merged**
